services:
  - type: web
    name: booklet-backend
    runtime: go
    env: go
    rootDir: backend
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/api
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: APP_ENV
        value: production
      - key: DB
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
